app:
  mode: "dev"
  grace: false
  host: "0.0.0.0"
  port: 4000
  read_timeout: "60s"
  write_timeout: "60s"
  idle_timeout: "60s"
  max_ping_count: 2
  jwt_secret: "Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5"
  tls:
    enabled: false # 是否开启https
    port: 443 # the https port
    cert_path: "" # the cert file (leave empty when using letsencrypt)
    key_path: "" # the cert key (leave empty when using letsencrypt)
  auto_tls:
    enabled: false # if the certificate should be requested from letsencrypt
    accept_tos: false # if you accept the tos from letsencrypt
    folder: "data/certs" # the directory of the cache from letsencrypt
    hosts: # the hosts for which letsencrypt should request certificates
      - example1.com
      - example2.com

database:
  dialect: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "gaia"
  ssl: false
  max_idle_conns: 0
  max_open_conns: 0
  logging: true
log:
  path: "/logs/gaia.log"
  level: "info"
  format: "json"
mail:
  enabled": true
  username": "yourGmailUsername"
  password": "yourGmailAppPassword"
  mail_server": "smtp.163.com"
  port": 587
  from": "from@gmail.com"
cache:
  type: "none"
  timeout: 60
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    key_prefix: "__:::gaia:"